### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by bmix** [mmaday/SublimeLinter-contrib-htmlhint#14]
When I installed *contrib-htmlhint* the first time (months ago) it was working okay, but since the update of SublimeLinter and the many deprecations, it did not. That did not change with the latest update of *contrib-htmlhint* either.

Debug output:
```
reloading plugin SublimeLinter-contrib-htmlhint.linter
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "S:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-htmlhint\linter.py", line 17, in <module>
    class Htmlhint(NodeLinter):
  File "S:\Users\bmix\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter-contrib-htmlhint\linter.py", line 30, in Htmlhint
    selector: 'text.html.basic'
NameError: name 'selector' is not defined
```

Config:

```json
"htmlhint":
{
	"selector": "text.html, text.html.basic",
	"disable": false,
	"args":
	[
	],
	"excludes":
	[
	]
}
```

* Windows 10 Home
* SublimeText 3.2.2, Build 3211
* htmlhint 0.11.0
* SublimeLinter-contrib-htmlhint 2.0.0
* SublimeLinter 4.13
* NodeJS v12.10.0
* system's Python is 3.5.3 (not sure, whether this is the one Sublime uses)

The only other linter, that shows this same behavior, is *contrib-csstree*. All other linters work fine.

On a sidenote, I realized, that the last time I installed *contrib-htmlhint* there was this message:

> This plugin currently only works with htmlhint versions 0.9.7 and prior.  Look for a new version to support 0.9.8 soon.

Could that be the problem?

P.S. It seems, the 'text.html' selector has been renamed into 'text.html.basic' in Sublime's HTML mode, at least, that's what I get when I hit `F1`

P.P.S. And thanks for keeping this updated :-)

**Comment by mmaday** [comment]
I just pushed a the 2.0.1 release.  When you pick it up, retry and let me know your results.
